# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Truxnell"

[social.params]
icon = "brand-github"

[[social]]
identifier = "mastodon"
name = "Fediverse"
url = "https://fedi.voltaicforge.com/"

[social.params]
icon = "brand-mastodon"

[[social]]
identifier = "tokenring"
name = "Token Webring"
url = "https://tokenring.monoxane.io/#voltaicforge"

[social.params]
icon = "tokenring-icon-dark"
